# Generated by Django 4.2.6 on 2023-10-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='star',
            new_name='price',
        ),
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
